Noticeboard/urls.py
from django.contrib import admin
from django.urls import path,include
from general.views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Home,name="home"),
    path('accounts/',include('accounts.urls')),
    path('general/',include('general.urls')),
]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/form.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('register/',views.Registration,name='registration'),
    path('creategroup/',views.CreateGroup,name='creategroup'),
    path('<slug>/',views.Groupview,name='group'),
    path("join/<slug>/",views.JoinGroup.as_view(),name="join"),
    path("leave/<slug>/",views.LeaveGroup.as_view(),name="leave"),
]

general/urls.py
from django.urls import path
from . import views
app_name = 'general'

urlpatterns = [
    path('<id>/',views.Eventview,name='event'),
    path('<slug>/createevent/',views.Eventform,name='createevent'),
    path('<id>/updateevent/',views.EventUpdateform,name='updateevent'),
    path('<id>/removeevent/',views.Eventdelete,name='removeevent'),
    path('question/<id>/',views.AnswerFaq,name='answerfaq'),
    path("predict/<id>/",views.predict,name="askquestion"),
    ]

accounts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django import template
from django.db import models
from django.utils.text import slugify

User = get_user_model()
register = template.Library()

class Group(models.Model):
    admin = models.CharField(max_length=255)
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    members = models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug=slugify(self.name)
        super(Group, self).save(*args, **kwargs)

    class Meta:
        ordering = ["name"]

class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name="memberships",on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name="user_groups",on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group","user")

class QuestionResponse(models.Model):
    question_id = models.AutoField(primary_key = True)
    question =  models.CharField(max_length=213, unique=False)
    is_response = models.BooleanField(default = False)
    response = models.CharField(max_length = 213, unique = False, null = True)
    frequency = models.PositiveSmallIntegerField(null = True)


# class QuestionMember(models.Model): #Contains details of users who asked a particular question

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ValidationError,EmailField,ModelForm
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from .models import Group

class UserCreateForm(UserCreationForm):
    email = EmailField(required=True)
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean_email(self):
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')
        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise ValidationError(u'This Email Address already holds an account.')
        return email

class CreatGroupForm(ModelForm):
    class Meta:
        fields = ("name",)
        model = Group
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

accounts/views.py
from django.shortcuts import render
from .forms import UserCreateForm,CreatGroupForm
from .models import Group,GroupMember
from general.models import Event
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import RedirectView
from django.shortcuts import get_object_or_404
from django.contrib.sites.shortcuts import get_current_site
# Create your views here.
def Registration(request):
    if request.method == 'POST':
        form = UserCreateForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            return HttpResponseRedirect(reverse('accounts:login'))
    else:
        form = UserCreateForm()
    return render(request,'accounts/form.html',{'form':form})

@login_required
def CreateGroup(request):
    if request.method == 'POST':
        form = CreatGroupForm(data=request.POST)
        if form.is_valid():
            group = form.save(commit=False)
            group.admin = request.user.username
            group.save()
            return HttpResponseRedirect(reverse('accounts:group',kwargs={"slug":group.slug}))
        else:
            print("Invalid")
    else:
        form = CreatGroupForm()

    return render(request, "accounts/form.html",{'form':form})

@login_required
def Groupview(request,slug):
    group = Group.objects.get(slug=slug)
    events = Event.objects.filter(group=group)
    current_site = get_current_site(request)
    return render(request, "accounts/groupview.html",{'group':group,
                                                      'current_site':current_site,
                                                      'events':events})

class JoinGroup(LoginRequiredMixin,RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("accounts:group",kwargs={"slug":self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except IntegrityError:
            return HttpResponse('User is already a member of the group')
        else:
            print("registered successfull")

        return super().get(request, *args, **kwargs)

class LeaveGroup(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("home")

    def get(self, request, *args, **kwargs):
        try:
            membership = GroupMember.objects.filter(
                user = self.request.user,
                group__slug = self.kwargs.get("slug")

            ).get()

        except GroupMember.DoesNotExist:
            return HttpResponse('You are not a member')

        else:
            membership.delete()
            print("successfully deleted")

        return super().get(request, *args, **kwargs)

accounts/templates/accounts/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="ripple-background">
  <div class="">

  </div>
  <div class="circle xxlarge shade1">

  </div>
  <div class="circle xlarge shade2">

  </div>
  <div class="circle large shade3">

  </div>
  <div class="circle mediun shade4">

  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-6">

    </div>
    <div class="col-6 mt-5">
      <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-light mt-3" name="button">Submit</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/groupview.html
{% extends "base.html" %}
{% block content %}
{% if group.admin == user.username %}
<ul class="nav justify-content-end bg-light">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'general:createevent' slug=group.slug %}">+ Create Event</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
  </li>
</ul>
{% endif %}
<div class="container">
  {% if group.admin == user.username %}
  <h2 class="text-white my-5">{{group.name}}</h2>

  <div class="my-3">
    You are the admin of the group
    <br>
    Share this link for your members to join
    <br>
    <span class="text-light text-decoration-underline">http://{{ current_site.domain }}{% url 'accounts:join' slug=group.slug %}</span>
  </div>
  {% elif user in group.members.all %}
  <h2 class="text-white my-5">{{group.name}}</h2>
  <a href="{% url 'accounts:leave' slug=group.slug %}"><button type="button" name="button">Leave Group</button></a>
  {% endif %}
  {% if events %}
  <h5 class="text-white">Events</h5>
  <table class="table w-75">
    <thead>
      <tr>
        <th scope="col">Title </th>
        <th scope="col">Description</th>
        <th scope="col">Timing</th>
      </tr>
    </thead>
    <tbody>
      {% for i in events %}
        <tr>
          <td scope="row"><a href="{% url 'general:event' id=i.id %}">{{ i.title }}</a></td>
          <td>{{ i.description }}</td>
          <td>{{ i.start_time }}-{{ i.end_time }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}
  {% if group.members.all %}
  <h5 class="text-white">Members</h5>
  <table class="table w-75">
    <thead>
      <tr>
        <th scope="col">Username </th>
        <th scope="col">Email</th>
      </tr>
    </thead>
    <tbody>
      {% for user in group.members.all %}
      <tr>
        <td scope="row">{{ user.username }}</td>
        <td>{{ user.email }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}
</div>
{% endblock %}