Noticeboard/urls.py
from django.contrib import admin
from django.urls import path,include
from general.views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Home,name="home"),
    path('accounts/',include('accounts.urls')),
    path('general/',include('general.urls')),
]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/form.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('register/',views.Registration,name='registration'),
    path('creategroup/',views.CreateGroup,name='creategroup'),
    path('<slug>/',views.Groupview,name='group'),
    path("join/<slug>/",views.JoinGroup.as_view(),name="join"),
    path("leave/<slug>/",views.LeaveGroup.as_view(),name="leave"),
]

general/urls.py
from django.urls import path
from . import views
app_name = 'general'

urlpatterns = [
    path('<id>/',views.Eventview,name='event'),
    path('<slug>/createevent/',views.Eventform,name='createevent'),
    path('<id>/updateevent/',views.EventUpdateform,name='updateevent'),
    path('<id>/removeevent/',views.Eventdelete,name='removeevent'),
    path('question/<id>/',views.AnswerFaq,name='answerfaq'),
    path("predict/<id>/",views.predict,name="askquestion"),
    ]

accounts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django import template
from django.db import models
from django.utils.text import slugify

User = get_user_model()
register = template.Library()

class Group(models.Model):
    admin = models.CharField(max_length=255)
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    members = models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug=slugify(self.name)
        super(Group, self).save(*args, **kwargs)

    class Meta:
        ordering = ["name"]

class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name="memberships",on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name="user_groups",on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group","user")

class QuestionResponse(models.Model):
    question_id = models.AutoField(primary_key = True)
    question =  models.CharField(max_length=213, unique=False)
    is_response = models.BooleanField(default = False)
    response = models.CharField(max_length = 213, unique = False, null = True)
    frequency = models.PositiveSmallIntegerField(null = True)


# class QuestionMember(models.Model): #Contains details of users who asked a particular question

general/models.py
from django.db import models
from django.contrib.auth import get_user_model
from accounts.models import Group
User = get_user_model()
# Create your models here.
class Event(models.Model):
    group = models.ForeignKey(Group,on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    start_time = models.DateTimeField(null=True,blank=True)
    end_time = models.DateTimeField()

    class Meta:
        ordering = ['start_time']


class FAQ(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    event = models.ForeignKey(Event,on_delete=models.CASCADE)
    question = models.TextField()
    answer = models.TextField(blank=True,null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_date']

templates/answerfaq.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h5>{{ faq.question }}</h5>
  <form method="post">
    {% csrf_token %}
    <textarea name="answer" rows="8" cols="80">{% if faq.answer %}{{ faq.answer }}{% endif %}</textarea>
    <button type="submit" name="button">Submit</button>
  </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>

{% load static %}
<html lang="en" dir="ltr">
  <head>


    <meta charset="utf-8">
    <title>Notice Board</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
        content="Responsive sidebar template with sliding effect and dropdown menu based on bootstrap 3">
    <title>Sidebar template</title>

    <!-- using online links -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
        integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel="stylesheet" href="//malihu.github.io/custom-scrollbar/jquery.mCustomScrollbar.min.css">

    <!-- using local links -->
    <!-- <link rel="stylesheet" href="../node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="../node_modules/@fortawesome/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="../node_modules/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css"> -->



    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/sidebar-themes.css' %}">

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <style media="screen">
    body{
      background: #3399ff;
    }


    .circle{
      position: absolute;
      border-radius: 50%;
      background: white;
      animation: ripple 15s infinite;
      box-shadow: 0px 0px 1px 0px #508fb9;
    }

    .small{
      width: 200px;
      height: 200px;
      left: -100px;
      bottom: -100px;
    }

    .medium{
      width: 400px;
      height: 400px;
      left: -200px;
      bottom: -200px;
    }

    .large{
      width: 600px;
      height: 600px;
      left: -300px;
      bottom: -300px;
    }

    .xlarge{
      width: 800px;
      height: 800px;
      left: -400px;
      bottom: -400px;
    }

    .xxlarge{
      width: 1000px;
      height: 1000px;
      left: -500px;
      bottom: -500px;
    }

    .shade1{
      opacity: 0.2;
    }
    .shade2{
      opacity: 0.5;
    }

    .shade3{
      opacity: 0.7;
    }

    .shade4{
      opacity: 0.8;
    }

    .shade5{
      opacity: 0.9;
    }

    @keyframes ripple{
      0%{
        transform: scale(0.8);
      }

      50%{
        transform: scale(1.2);
      }

      100%{
        transform: scale(0.8);
      }
    }
    </style>
  </head>
  <body>
    {% block content %}
    {% endblock %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous">
    </script>
    <script src="//malihu.github.io/custom-scrollbar/jquery.mCustomScrollbar.concat.min.js"></script>

<script src="{% static 'js/main.js' %}"></script>
  </body>

</html>

templates/eventview.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% if event.group.admin == user.username %}
<ul class="nav justify-content-end bg-light">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'general:updateevent' id=event.id %}">Update Event</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'general:removeevent' id=event.id %}">Remove Event</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
  </li>
</ul>
{% endif %}
<div class="container">
  <h3>{{ event.title }}</h3>
  <p>{{ event.description }}</p>
  <h5>Timing : {{ event.start_time }}-{{ event.end_time }}</h5>
  {% if event.group.admin == user.username %}
  {% for i in faqs %}
  <a href="{% url 'general:answerfaq' id=i.id %}">{{ i.question }}{{ i.created_date }}</a><br>
  {% if i.answer %}<p>{{ i.answer }}{{ i.modified_date }}</p>{% endif %}

  {% endfor %}
  {% elif user in event.group.members.all %}
  {% for i in faqs %}
  <p>{{ i.question }}{{ i.created_date }}</p>
  {% if i.answer %}<p>{{ i.answer }}{{ i.modified_date }}</p>{% endif %}
  {% endfor %}
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-light mt-3" name="button">Ask</button>
  </form>
  {% endif %}
</div>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
<div class="page-wrapper default-theme sidebar-bg bg1 toggled">
    <nav id="sidebar" class="sidebar-wrapper">
        <div class="sidebar-content">
            <div class="sidebar-item sidebar-header d-flex flex-nowrap">

                <div class="user-info">
                    <span class="user-name">{{ user.username }}
                    </span>
                    <span class="user-role">Administrator</span>
                    <span class="user-status">
                        <i class="fa fa-circle"></i>
                        <span>Online</span>
                    </span>
                </div>
            </div>
            <!-- sidebar-search  -->

            <!-- sidebar-menu  -->
            <div class=" sidebar-item sidebar-menu">
                <ul>
                    <a href="{% url 'home' %}">

                        <li class="header-menu">
                            <span>Home</span>
                        </li>
                    </a>

                    <li class="header-menu">
                        <span>Groups</span>
                    </li>
                    {% if admin_groups %}
                    <li class="sidebar-dropdown">
                        <a href="#" aria-haspopup="true">
                            <span class="badge-sonar"></span>
                            <span class="menu-text">Admin Groups</span>
                        </a>
                        <div class="sidebar-submenu">
                            <ul>
                              {% for i in admin_groups %}
                                <li>
                                    <li class="sidebar-dropdown">
                                        <a href="{% url 'accounts:group' slug=i.slug %}" aria-haspopup="true" aria-expanded="false">{{ i.name }}
                                            <span class="badge badge-pill badge-success">3</span>
                                        </a>

                                    </li>

                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </li>
                    {% endif %}
                    {% if member_groups %}
                    <li class="sidebar-dropdown">
                        <a href="#" aria-haspopup="true">
                            <span class="badge-sonar"></span>
                            <span class="menu-text">Member Groups</span>
                        </a>
                        <div class="sidebar-submenu">
                            <ul>
                              {% for i in member_groups %}
                                <li>
                                    <li class="sidebar-dropdown">
                                        <a href="{% url 'accounts:group' slug=i.group.slug %}" aria-haspopup="true" aria-expanded="false">{{ i.group.name }}
                                            <span class="badge badge-pill badge-success">3</span>
                                        </a>

                                    </li>

                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </li>
                    {% endif %}



                    <li class="header-menu">
                        <span>New Group</span>
                    </li>
                    <li>
                        <a href="{% url 'accounts:creategroup' %}">
                            <span class="menu-text">+ Create Group</span>
                        </a>
                    </li>

                </ul>
            </div>
            <!-- sidebar-menu  -->
        </div>
        <!-- sidebar-footer  -->
        <div class="sidebar-footer">
            <div>

                <a  href="{% url 'accounts:logout' %}">
                    <i class="fa fa-power-off"></i>
                </a>
            </div>
            <!--
            <div class="pinned-footer">
                <a href="#">
                    <i class="fas fa-ellipsis-h"></i>
                </a>
            </div>-->
        </div>
    </nav>
    <!-- page-content  -->
    <main class="page-content pt-2">

        <!--
        <div id="overlay" class="overlay"></div>
        <div class="container-fluid p-5">
            <div class="row">
                <div class="form-group col-md-12">
                    <h2>Pro Sidebar</h2>
                    <p>This is a responsive sidebar template with dropdown menu based on bootstrap framework.</p>

                </div>
                <div class="form-group col-md-12">
                    <iframe
                        src="https://ghbtns.com/github-btn.html?user=azouaoui-med&repo=pro-sidebar-template&type=star&count=true&size=small"
                        frameborder="0" scrolling="0" width="100px" height="30px"></iframe>
                    <iframe
                        src="https://ghbtns.com/github-btn.html?user=azouaoui-med&repo=pro-sidebar-template&type=fork&count=true&size=small"
                        frameborder="0" scrolling="0" width="100px" height="30px"></iframe>
                </div>

                <div class="form-group col-md-12">
                    <a id="toggle-sidebar" class="btn btn-secondary rounded-0" href="#">
                        <span>Toggle Sidebar</span>
                    </a>
                    <a id="pin-sidebar" class="btn btn-outline-secondary rounded-0" href="#">
                        <span>Pin Sidebar</span>
                    </a>

                </div>
            </div>
            <hr>
            <div class="row">
                <div class="form-group col-md-12">
                    <h3>Themes</h3>
                    <p>Here are more themes that you can use</p>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-12">
                    <a href="#" data-theme="default-theme" class="theme default-theme selected"></a>
                    <a href="#" data-theme="chiller-theme" class="theme chiller-theme"></a>
                    <a href="#" data-theme="legacy-theme" class="theme legacy-theme"></a>
                    <a href="#" data-theme="ice-theme" class="theme ice-theme"></a>
                    <a href="#" data-theme="cool-theme" class="theme cool-theme"></a>
                    <a href="#" data-theme="light-theme" class="theme light-theme"></a>
                </div>
                <div class="form-group col-md-12">
                    <p>You can also use background image </p>
                </div>

                <div class="form-group col-md-12">
                    <a href="#" data-bg="bg1" class="theme theme-bg "></a>
                    <a href="#" data-bg="bg2" class="theme theme-bg"></a>
                    <a href="#" data-bg="bg3" class="theme theme-bg"></a>
                    <a href="#" data-bg="bg4" class="theme theme-bg"></a>
                </div>

                <div class="form-group col-md-12">
                    <div class="custom-control custom-switch">
                        <input type="checkbox" class="custom-control-input" id="toggle-bg" checked>
                        <label class="custom-control-label" for="toggle-bg">Background image</label>
                    </div>
                </div>

                <div class="form-group col-md-12">
                    <div class="custom-control custom-switch">
                        <input type="checkbox" class="custom-control-input" id="toggle-border-radius">
                        <label class="custom-control-label" for="toggle-border-radius">Border radius</label>
                    </div>
                </div>

            </div>


            <hr>
            <div class="row ">
                <div class="form-group col-md-12">
                    <small>Made with <i class="fa fa-heart text-danger" aria-hidden="true"></i> by <span
                            class="text-secondary font-weight-bold">Mohamed
                            Azouaoui</span></small>
                </div>
                <div class="form-group col-md-12">
                    <a href="https://github.com/azouaoui-med" target="_blank"
                        class="btn btn-sm bg-secondary shadow-sm rounded-0 text-light mr-3 mb-3">
                        <i class="fab fa-github" aria-hidden="true"></i>
                    </a>
                    <a href="https://twitter.com/azouaoui_med" target="_blank"
                        class="btn btn-sm bg-secondary shadow-sm rounded-0 text-light mr-3 mb-3">
                        <i class="fab fa-twitter" aria-hidden="true"></i>
                    </a>
                    <a href="https://www.instagram.com/azouaoui_med/" target="_blank"
                        class="btn btn-sm bg-secondary shadow-sm rounded-0 text-light mr-3 mb-3">
                        <i class="fab fa-instagram" aria-hidden="true"></i>
                    </a>
                    <a href="https://www.linkedin.com/in/mohamed-azouaoui/" target="_blank"
                        class="btn btn-sm bg-secondary shadow-sm rounded-0 text-light mr-3 mb-3">
                        <i class="fab fa-linkedin-in" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
        </div>
    -->
    </main>
    <!-- page-content" -->
</div>
<!-- page-wrapper -->

{% if admin_groups %}
<h3 class="text-warning bg-white p-2 text-wrap w-25 m-3">Groups (Admin)</h3>
<ul>
  {% for i in admin_groups %}
  <a class="text-white" href="{% url 'accounts:group' slug=i.slug %}">
    <li>{{i.name}}</li>
  </a>
  {% endfor %}
</ul>
{% endif %}
{% if member_groups %}
<h3 class="text-warning bg-white p-2 text-wrap w-25 m-3">Groups (Member)</h3>
<ul>
  {% for i in member_groups %}
  <a class="text-white" href="{% url 'accounts:group' slug=i.group.slug %}">
    <li>{{i.group.name}}</li>
  </a>
  {% endfor %}
</ul>
{% endif %}
{% else %}
<div class="ripple-background">
  <div class="">

  </div>
  <div class="circle xxlarge shade1">

  </div>
  <div class="circle xlarge shade2">

  </div>
  <div class="circle large shade3">

  </div>
  <div class="circle mediun shade4">

  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-6">

    </div>
    <div class="col-6">
      <h1 class="text-white mx-3 mt-5">NOTICE BOARD</h1>
      <p class="text-light m-3 w-75">Team Randumb meets you with a powerful notification and timeline management tool to keep you on track and also helps you better to get your questionnaire answered from your admin</p>
      <a href="{% url 'accounts:login' %}"><button type="button" class="m-3 btn btn-light btn-lg" name="button">Login</button></a>
      <a href="{% url 'accounts:registration' %}"><button type="button" class="m-3 btn btn-light btn-lg" name="button">Register</button></a>
    </div>
  </div>
</div>

{% endif %}
{% endblock %}

templates/model.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-6">

    </div>
    <div class="col-6 mt-5">
      <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-outline-primary mt-3" name="button">Submit</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}